=== DZunke/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.heigl.org"
           xmlns="https://www.heigl.org"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="holidays">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DZunke/holidayChecker/share/SE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">Nyårsdagen</date>
    <date day="6" month="1" free="true">Trettondedag jul</date>
    <easter offset="-2" free="true">Långfredagen</easter>
    <easter offset="0" free="true">påskdagen</easter>
    <easter offset="1" free="true">Annandag påsk</easter>
    <date day="1" month="5" free="true">Första Maj</date>
    <easter offset="39" free="true">Kristi himmelsfärds dag</easter>
    <date day="6" month="6" free="true">Sveriges nationaldag</date>
    <easter offset="49" free="true">pingstdagen</easter>
    <relative day="18" month="6" relation="next friday" free="true">midsommarafton</relative>
    <relative day="19" month="6" relation="next saturday" free="true">Midsommardagen</relative>
    <relative day="30" month="10" relation="next saturday" free="true">Alla helgons dag</relative>
    <date day="24" month="12" free="true" comment="shops are closed">julafton</date>
    <date day="25" month="12" free="true">Juldagen</date>
    <date day="26" month="12" free="true">Annandag jul</date>
    <date day="31" month="12" free="true" comment="Shops close at 3PM">nyårsafton</date>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Sweden" lastChecked="2020-12-19">Wikipedia</resource>
    </resources>
</holidays>

=== DZunke/holidayChecker/share/AM.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Armenia" lastChecked="2022-10-14">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true" comment="New Year's Day">Ամանոր</date>
    <date day="2" month="1" free="true" comment="New Year's Day">Ամանոր</date>
    <date day="6" month="1" free="true" comment="Christmas Day">Սուրբ Ծնունդ</date>
    <date day="28" month="1" free="true" comment="Army Day">Բանակի օր</date>
    <date day="8" month="3" free="true" comment="Womens Day">Կանանց տոն</date>
    <date day="24" month="4" free="true" comment="Armenian Genozide Rememberance Day">Եղեռնի զոհերի հիշատակի օր</date>
    <date day="1" month="5" free="true" comment="Labour Day">Աշխատանքի օր</date>
    <date day="9" month="5" free="true" comment="Victory and Peace Day">Հաղթանակի եւ Խաղաղության տոն</date>
    <date day="28" month="5" free="true" comment="Republic Day">Հանրապետության օր</date>
    <date day="5" month="7" free="true" comment="Constitution Day">Սահմանադրության օր</date>
    <date day="21" month="9" free="true" comment="Independence Day">Անկախության օր</date>
    <date day="31" month="12" free="true" comment="New Year'S Eve">Ամանոր</date>
</holidays>

=== DZunke/holidayChecker/share/fr_LU.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true">Jour de l'an</date>
    <easter offset="0" free="false">Pâques</easter>
    <easter offset="1" free="true">Lundi de Pâques</easter>
    <date day="1" month="5" free="true">Fête du Travail</date>
    <easter offset="40" free="true">Ascension</easter>
    <easter offset="49" free="true">Pentecôte</easter>
    <easter offset="50" free="true">Lundi de Pentecôte</easter>
    <date day="23" month="6" free="true">Fête nationale</date>
    <date day="15" month="8" free="true">Assomption</date>
    <date day="1" month="11" free="true">Toussaint</date>
    <date day="25" month="12" free="true">Noël</date>
    <date day="26" month="12" free="true">St.Etienne</date>
</holidays>

=== DZunke/holidayChecker/share/CD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
		<resources>
				<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_the_Democratic_Republic_of_the_Congo" lastChecked="2022-10-27">Wikipedia</resource>
		</resources>

		<!-- Statutory holidays -->
    <date day="1" month="1" free="true">New Year's Day</date>
    <date day="4" month="1" free="true">Martyrs Day</date>
    <date day="16" month="1" free="true">Laurent-Désiré Kabila Assassination</date>
    <date day="17" month="1" free="true">Patrice Lumumba Assassination</date>
    <date day="1" month="5" free="true">Labor Day</date>
    <date day="17" month="5" free="true">Liberation Day</date>
    <date day="30" month="6" free="true">Independence Day</date>
    <date day="1" month="8" free="true">Parents' Day</date>
    <date day="17" month="11" free="true">Army Day</date>
    <date day="25" month="12" free="true">Christmas Day</date>
</holidays>

=== DZunke/holidayChecker/share/GB.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true">New Year's Day</date>
    <easter offset="-2" free="true">Good Friday</easter>
    <easter offset="1" free="true">Easter Monday</easter>
    <easter offset="0" free="false">Easter Sunday</easter>
    <relative day="30" month="4" relation="next monday" free="true">Early May Bank Holiday</relative>
    <relative day="1" month="6" relation="previous monday" free="true">Spring Bank Holiday</relative>
    <dateFollowUp day="25" month="12" free="true" followup="tuesday">Christmas Day</dateFollowUp>
    <dateFollowUp day="26" month="12" free="true" followup="monday">Boxing Day</dateFollowUp>
</holidays>

=== DZunke/holidayChecker/share/en_IE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude">
    <date day="1" month="1" free="true">New Year's Day</date>
    <date day="17" month="3" free="true">Saint Patrick's Day</date>
    <easter offset="1" free="true">Easter Monday</easter>
    <relative day="1" month="5" relation="first monday" free="true">May Day</relative>
    <relative day="1" month="6" relation="first monday" free="true">June Holiday</relative>
    <relative day="1" month="8" relation="first monday" free="true">August Holiday</relative>
    <relative day="1" month="8" relation="last monday" free="true">October Holiday</relative>
    <date day="25" month="12" free="true">Christmas Day</date>
    <date day="26" month="12" free="true">Saint Stephen's Day</date>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_the_Republic_of_Ireland" lastChecked="2020-12-19">Wikipedia</resource>
    </resources>
</holidays>

=== DZunke/holidayChecker/share/KH.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Cambodia" lastChecked="2022-10-26">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">ទិវាបុណ្យចូលឆ្នាំសកល</date>
	<date day="7" month="1" free="true" comment="Victory Over the Genocidal Regime Day">ទិវាជ័យជម្នះលើរបបប្រល័យពូជសាសន៍</date>
	<date day="8" month="3" free="true" comment="International Womens Day">ទិវានារីអន្តរជាតិ</date>
	<!-- TODO: Base on correct calendar! -->
	<date day="14" month="4" free="true" comment="Cambodian New Year">ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ</date>
	<date day="15" month="4" free="true" comment="Cambodian New Year">ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ</date>
	<date day="16" month="4" free="true" comment="Cambodian New Year">ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ</date>
	<!-- TODO: Base on correct calendar and use correct day and month (fullmoon of Vaisakha)! -->
	<date day="16" month="5" year="2022" free="true" comment="Visakh Bochea">ពិធីបុណ្យវិសាខបូជា</date>
	<date day="1" month="5" free="true" comment="Labour Day">ទិវាពលកម្មអន្តរជាតិ</date>
	<!-- TODO: Base on correct calendar and use correct day and month (4th day of the 6th months wanning moon) -->
	<!-- <date day="4" month="6" free="true" comment="Royal Ploughing Ceremony">ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល</date> -->
	<date day="14" month="5" free="true" comment="King Sihamoni's Birthday">ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្មព្រះករុណាព្រះបាទសម្ដេចព្រះបរមនាថ នរោត្ដម សីហមុនី</date>
	<date day="20" month="5" free="true" comment="National Day of Remembrance">ទិវាជាតិនៃការចងចាំ</date>
	<date day="18" month="6" free="true" comment="Queen Mother's Birthday">ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្មព្រះមហាក្សត្រី នរោត្ដម មុនីនាថ សីហនុ</date>
	<date day="24" month="9" free="true" comment="Constitution Day">ទិវាប្រកាសរដ្ឋធម្មនុញ្ញ</date>
	<!-- TODO: Base on correct calendar "khmer"-->
	<!-- <date day="15" month="10" free="true" comment="Pchum Ben">ពិធីបុណ្យភ្ជុំបិណ្ឌ</date> -->
	<!-- <date day="16" month="10" free="true" comment="Pchum Ben">ពិធីបុណ្យភ្ជុំបិណ្ឌ</date> -->
	<!-- <date day="17" month="10" free="true" comment="Pchum Ben">ពិធីបុណ្យភ្ជុំបិណ្ឌ</date> -->
	<date day="15" month="10" free="true" comment="Commemoration Day of the King's Father">ព្រះរាជពិធីគោរពព្រះវិញ្ញាណក្ខន្ធព្រះករុណាព្រះបាទសម្ដេចព្រះ នរោត្ដម សីហនុ</date>
	<date day="29" month="10" free="true" comment="Coronation day of King Sihamoni">ព្រះរាជពិធីគ្រងព្រះបរមរាជសម្បត្តិរបស់ព្រះករុណាព្រះបាទសម្ដេចព្រះបរមនាថ នរោត្ដម សីហមុនី</date>
	<date day="9" month="11" free="true" comment="Independence Day">ទិវាបុណ្យឯករាជ្យជាតិ</date>
	<!-- TODO: Base on correct calendar and use correct date -->
	<date day="18" month="11" year="2021" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="19" month="11" year="2021" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="20" month="11" year="2021" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="7" month="11" year="2022" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="8" month="11" year="2022" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="9" month="11" year="2022" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="26" month="11" year="2023" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="27" month="11" year="2023" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
	<date day="28" month="11" year="2023" free="true" comment="Water Festival">ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ</date>
</holidays>

=== DZunke/holidayChecker/share/CC.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands" lastChecked="2022-10-19">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true">New Year's Day</date>
    <date day="26" month="1" free="true">Australia Day</date>
    <easter offset="-2" free="true">Good Friday</easter>
    <easter offset="1" free="true">Easter Monday</easter>
    <date day="6" month="4" free="true">Self Determination Day</date>
    <date day="25" month="4" free="true">Anzac Day</date>
    <date day="1" month="10" free="true" calendar="islamic-civil">Hari Raya Puasa</date>
    <date day="10" month="12" free="true" calendar="islamic-civil">Hari Raya Haji</date>
    <date day="1" month="1" free="true" calendar="islamic-civil">Islamic New Year</date>
    <date day="12" month="3" free="true" calendar="islamic-civil">Hari Maulaud Nabi</date>
    <date day="25" month="12" free="true">Christmas Day</date>
    <date day="26" month="12" free="true">Boxing Day</date>
</holidays>
