=== DZunke/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.heigl.org"
           xmlns="https://www.heigl.org"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="holidays">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DZunke/holidayChecker/share/BO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Bolivia" lastChecked="2022-10-23">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">Año Nuevo </date>
	<date day="22" month="1" free="true">Nacimiento del Estado Plurinacional de Bolivia</date>
	<date day="2" month="2" free="true">Fiesta de la Virgen de Candelaria </date>
	<date day="1" month="3" free="true">Feriado por Carnaval</date>
	<date day="2" month="3" free="true">Feriado por Carnaval</date>
	<easter offset="-2" free="true">Viernes Santo</easter>
	<easter offset="60" free="true">Corpus Christi</easter>
	<date day="1" month="5" free="true" forwardwhen="sunday" forwardto="monday">Dia del trabajo</date>
	<date day="21" month="6" free="true" comment="Andean New Year">Año Nuevo Andino</date>
	<date day="2" month="8" free="true">Día de la Revolución Agraria, Productiva y Comunitaria</date>
	<date day="6" month="8" free="true">Dia de la Patria</date>
	<date day="2" month="11" free="true">Todos Santos</date>
	<date day="25" month="12" free="true">Navidad</date>
</holidays>

=== DZunke/holidayChecker/share/BD-islam.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<date day="10" month="1" free="true" calendar="islamic-umalqura" comment="Ashura">আশুরা</date>
	<date day="12" month="3" free="true" calendar="islamic-umalqura" comment="Eid-e-Miladun-Nabi">ঈদে মিলাদুন্নবী</date>
	<date day="1" month="10" free="true" calendar="islamic-umalqura" comment="Eid ul-Fitr">ঈদুল ফিতর</date>
	<date day="2" month="10" free="true" calendar="islamic-umalqura" comment="Eid ul-Fitr">ঈদুল ফিতর</date>
	<date day="3" month="10" free="true" calendar="islamic-umalqura" comment="Eid ul-Fitr">ঈদুল ফিতর</date>
	<date day="10" month="12" free="true" calendar="islamic-umalqura" comment="Eid ul-Adha">ঈদুল আযহা</date>
	<date day="11" month="12" free="true" calendar="islamic-umalqura" comment="Eid ul-Adha">ঈদুল আযহা</date>
	<date day="12" month="12" free="true" calendar="islamic-umalqura" comment="Eid ul-Adha">ঈদুল আযহা</date>
	<xi:include href="BD.xml" parse="xml" xpointer="xpointer(*/*)">
		<xi:fallback></xi:fallback>
	</xi:include>
</holidays>

=== DZunke/holidayChecker/share/BB.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<date day="1" month="1" free="true">New Year's Eve</date>
	<date day="21" month="1" free="true">Errol Barrow Day</date>
	<easter offset="-2" free="true">Good Friday</easter>
	<easter offset="1" free="true">Easter Monday</easter>
	<date day="28" month="4" free="true">National Heroes' Day</date>
	<date day="1" month="5" free="true">May Day/Labour Day</date>
	<easter offset="50" free="true">Whit Monday</easter>
	<date day="1" month="8" free="true">Emancipation Day</date>
	<relative day="31" month="7" relation="next monday" free="true">Kadooment Day</relative>
	<date day="30" month="11" free="true">Independence Day</date>
	<date day="25" month="12" free="true">Christmas Day</date>
	<date day="26" month="12" free="true">Boxing Day</date>
</holidays>

=== DZunke/holidayChecker/share/BM.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
	<date day="1" month="1" free="true">New Year's Day</date>
	<easter offset="-2" free="true">Good Friday</easter>
	<relative day="1" month="5" free="true" relation="last friday of may">Bermuda Day</relative>
	<relative day="1" month="6" relation="third monday of june" free="true" firstobservance="2008">National Heroes Day</relative>
	<relative day="1" month="8" relation="first monday of august" free="true" rewindwhen="monday" rewindto="thursday">Emancipation Day</relative>
	<relative day="1" month="8" relation="first monday of august" free="true" rewindwhen="monday" rewindto="friday">Somers' Day</relative>
	<relative day="1" month="9" relation="first monday of september" free="true">Labour Day</relative>
	<date day="11" month="11" free="true">Remembrance Day</date>
	<date day="25" month="12" free="true">Christmas Day</date>
	<date day="26" month="12" free="true">Boxing Day</date>
</holidays>

=== DZunke/holidayChecker/share/DK.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">Nytårsdag</date>
    <easter offset="-7" free="true">Palmesøndag</easter>
    <easter offset="-3" free="true">Skærtorsdag</easter>
    <easter offset="-2" free="true">Langfredag</easter>
    <easter offset="0" free="true">Påskedag</easter>
    <easter offset="1" free="true">Anden påskedag</easter>
    <easter offset="25" free="true">Store bededag</easter>
    <easter offset="39" free="true">Kristi Himmelfartsdag</easter>
    <easter offset="49" free="true">Pinsedag</easter>
    <easter offset="50" free="true">Anden Pinsedag</easter>
    <date day="5" month="6" free="true">Grundlovsdag</date>
    <date day="24" month="12" free="true" comment="shops are closed">Juleaften</date>
    <date day="25" month="12" free="true">Juledag</date>
    <date day="26" month="12" free="true">Anden juledag</date>
    <date day="31" month="12" free="true" comment="Shops close at 3PM">Nytårsaften</date>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Denmark" lastChecked="2020-12-19">Wikipedia</resource>
    </resources>
</holidays>

=== DZunke/holidayChecker/share/BH.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<date day="1" month="1" free="true" comment="New Year's Day">رأس السنة الميلادية</date>
	<date day="12" month="3" free="true" calendar="islamic-umalqura" comment="Prophet Muhammad's Birthday">المولد النبوي</date>
	<date day="1" month="5" free="true" comment="Labour Day">يوم العمال</date>
	<date day="1" month="10" free="true" calendar="islamic-umalqura" comment="Little Feast">عيد الفطر</date>
	<date day="2" month="10" free="true" calendar="islamic-umalqura" comment="Little Feast">عيد الفطر</date>
	<date day="3" month="10" free="true" calendar="islamic-umalqura" comment="Little Feast">عيد الفطر</date>
	<date day="9" month="12" free="true" calendar="islamic-umalqura" comment="Arafat Day">يوم عرفة</date>
	<date day="10" month="12" free="true" calendar="islamic-umalqura" comment="Feast of the sacrifice">عيد الأضحى</date>
	<date day="11" month="12" free="true" calendar="islamic-umalqura" comment="Feast of the sacrifice">عيد الأضحى</date>
	<date day="12" month="12" free="true" calendar="islamic-umalqura" comment="Feast of the sacrifice">عيد الأضحى</date>
	<date day="1" month="1" free="true" calendar="islamic-umalqura" comment="Islamic New Year">رأس السنة الهجرية</date>
	<date day="9" month="1" free="true" calendar="islamic-umalqura" comment="DAy of Ashura">عاشوراء</date>
	<date day="10" month="1" free="true" calendar="islamic-umalqura" comment="DAy of Ashura">عاشوراء</date>
	<date day="16" month="12" free="true" comment="National Day">اليوم الوطني</date>
	<date day="17" month="12" free="true" comment="Acession Day">يوم الجلوس</date>
</holidays>

=== DZunke/holidayChecker/share/RU.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true" comment="New years">Новый год</date>
    <date day="2" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="3" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="4" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="5" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="6" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="7" month="1" free="true" comment="New years holidays">Рождество Христово</date>
    <date day="8" month="1" free="true" comment="New years holidays">Новогодние каникулы</date>
    <date day="23" month="2" free="true" comment="Motherland defenders day">День защитников отечества</date>
    <date day="8" month="3" free="true" comment="International Women's Day">Международный женский день</date>
    <date day="1" month="5" free="true" comment="Labour day">День международной солидарности трудящихся</date>
    <date day="9" month="5" free="true" comment="Victory day">День победы</date>
    <date day="12" month="6" free="true" comment="Russia Day">День России</date>
    <date day="22" month="8" free="true" comment="National Flag Day">National FLag Day</date>
    <date day="4" month="11" free="true" comment="National Unity Day">День народного единства</date>
    <date day="31" month="12" free="true" comment="New years eve">Новый год</date>
</holidays>

=== DZunke/holidayChecker/share/en_DZ.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Algeria" lastChecked="2022-10-11">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true">New Year's Day</date>
    <date day="12" month="1" free="true">Amazigh New Year</date>
    <date day="1" month="5" free="true">Labour Day</date>
    <date day="5" month="7" free="true">Independence Day</date>
    <date day="1" month="11" free="true">Revolution Day</date>
    <date day="1" month="1" free="true" calendar="islamic-civil">Islamic New Year</date>
    <date day="10" month="1" free="true" calendar="islamic-civil">Ashura</date>
    <date day="12" month="3" free="true" calendar="islamic-civil">Mawlid</date>
    <date calendar="islamic-civil" day="1" month="10" free="true" comment="Eid al-Fitr">Eid al-Fitr</date>
    <date calendar="islamic-civil" day="10" month="12" free="true" comment="Eid al-Adha">Eid al-Adha</date>
</holidays>
