=== DZunke/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.heigl.org"
           xmlns="https://www.heigl.org"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="holidays">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DZunke/holidayChecker/share/fr_CA-YT.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/holidays https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="fr_CA.xml" xpointer="xpointer(*/*)">
        <xi:fallback/>
    </xi:include>
    <relative day="25" month="5" relation="previous monday" free="true">Fête de la Reine</relative>
    <date day="21" month="6" free="true">Journée nationale des Autochthones</date>
    <date day="24" month="6" free="true">Saint-Jean-Baptiste</date>
    <relative day="1" month="8" relation="first monday of this month" free="true">Fête du patrimoine</relative>
    <relative day="1" month="8" relation="third monday of this month" free="true">Jour de la Découverte</relative>
    <relative day="1" month="10" relation="second monday of this month" free="true">Action de grâce</relative>
    <date day="11" month="11" free="true">Jour du Souvenir</date>
</holidays>

=== DZunke/holidayChecker/share/CX.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Christmas_Island" lastChecked="2022-10-19">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true">New Year's Day</date>
    <date day="26" month="1" free="true">Australia Day</date>
    <date day="1" month="1" free="true" calendar="chinese">Chinese New Year</date>
    <date day="2" month="1" free="true" calendar="chinese">Chinese New Year</date>
    <relative day="1" month="3" relation="fourth monday" free="true">Labour Day</relative>
    <easter offset="-2" free="true">Good Friday</easter>
    <date day="25" month="4" free="true">Anzac Day</date>
    <date day="1" month="10" free="true" calendar="islamic-civil">Eid al-Fitr</date>
    <date day="10" month="12" free="true" calendar="islamic-civil">Eid al-Adha</date>
    <date day="6" month="10" free="true">Territory Day</date>
    <date day="25" month="12" free="true">Christmas Day</date>
    <date day="26" month="12" free="true">Boxing Day</date>
</holidays>

=== DZunke/holidayChecker/share/MX.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
		<resources>
				<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Mexico" lastChecked="2022-10-26">Wikipedia</resource>
		</resources>

		<!-- Statutory holidays -->
    <date day="1" month="1" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="New Year's Day">Año Nuevo</date>
    <relative day="1" month="2" relation="first monday of this month" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Constitution Day">Día de la Constitución</relative>
    <date day="21" month="3" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Benito Juárez's Birthday">Natalicio de Benito Juárez</date>
    <date day="1" month="5" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Labour Day">Día del Trabajo</date>
    <date day="16" month="9" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Independence Day">Día de la Independencia</date>
    <date day="20" month="11" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Revolution Day">Día de la Revolución</date>
    <date day="25" month="12" forwardto="monday" forwardwhen="sunday" rewindto="friday" rewindwhen="saturday" free="true" comment="Christmas Day">Navidad</date>

		<!-- Civic holidays -->
    <date day="20" month="2" free="false" comment="Mexican Army Day">Día del Ejército</date>
    <date day="24" month="2" free="false" comment="Flag Day">Día de la Bandera</date>
    <date day="18" month="3" free="false" comment="Anniversary of the Oil Expropriation">Aniversario de la Expropiación petrolera</date>
    <date day="21" month="4" free="false" comment="Heroic Defense of Veracruz">Heroica Defensa de Veracruz</date>
    <date day="5" month="5" free="false" comment="Fifth of May">Cinco de Mayo</date>
    <date day="8" month="5" free="false" comment="Miguel Hidalgo's birthday">Natalicio de Miguel Hidalgo</date>
    <date day="1" month="6" free="false" comment="National Maritime Day">Día de la Marina</date>
    <date day="13" month="9" free="false" comment="Anniversary of the 'Boy Heroes' or 'Heroic Cadets'">Día de los Niños Héroes</date>
    <date day="16" month="9" free="false" comment="Cry of Dolores">Grito de Dolores</date>
    <date day="27" month="9" free="false" comment="Culmination of the Mexican War of Independence">Consumación de la Independencia</date>
    <date day="30" month="9" free="false" comment="Morelos' birthday">Natalicio de José Mª Morelos y Pavón</date>
    <date day="23" month="11" free="false" comment="Mexican Navy Day">Dia de la Armada de Mexico</date>

		<!-- Festivities -->
		<date day="6" month="1" free="false" comment="Epiphany">Día de los Reyes Magos</date>
		<date day="2" month="2" free="false" comment="Candlemas">Día de la Candelaria</date>
		<easter offset="52" free="false" comment="Carnival">Carnaval</easter>
		<easter offset="51" free="false" comment="Carnival">Carnaval</easter>
		<easter offset="50" free="false" comment="Carnival">Carnaval</easter>
		<easter offset="49" free="false" comment="Carnival">Carnaval</easter>
		<easter offset="48" free="false" comment="Carnival">Carnaval</easter>
		<easter offset="47" free="false" comment="Carnival">Carnaval</easter>
		<date day="14" month="2" free="false" comment="Valentine's Day">Día del Amor y la Amistad</date>
		<date day="8" month="3" free="false" comment="International Women's Day">Día Internacional de la Mujer</date>
		<easter offset="-3"  free="false" comment="Holy Thursday">Jueves Santo</easter>
		<easter offset="-2" free="false" comment="Good Friday">Viernes Santo</easter>
		<date day="30" month="4" free="false" comment="Children's Day">Día del Niño</date>
		<date day="10" month="5" free="false" comment="Mother's Day">Día de las Madres</date>
		<date day="15" month="5" free="false" comment="Teacher's Day">Día del Maestros</date>
		<date day="23" month="5" free="false" comment="Students' Day">Día del estudiante</date>
		<relative day="1" month="6" relation="third sunday of this month" free="false" comment="Father's Day">Día del Padre</relative>
		<date day="1" month="11" free="false" comment="All Saints' Day (Day of the Dead)">Día de Todos los Santos</date>
		<date day="2" month="11" free="false" comment="All Souls' Day (Day of the Dead)">Día de Muertos</date>
		<date day="12" month="12" free="false" comment="Feast of Our Lady of Guadalupe">Día de la Virgen de Guadalupe</date>
		<date day="16" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="17" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="18" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="19" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="20" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="21" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="22" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="23" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="24" month="12" free="false" comment="Las Posadas">Las Posadas</date>
		<date day="24" month="12" free="false" comment="Christmas Eve">Nochebuena</date>
		<date day="28" month="12" free="false" comment="Holy Innocents Day">Día de los Santos Inocentes</date>
		<date day="31" month="12" free="false" comment="New Year's Eve">Víspera de Año Nuevo</date>
</holidays>

=== DZunke/holidayChecker/share/FI.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true">Uudenvuodenpäivä</date>
    <date day="6" month="1" free="true">Loppiainen</date>
    <easter offset="-7" free="false">Palmusunnuntai</easter>
    <easter offset="-2" free="true">Pitkäperjantai</easter>
    <easter offset="0" free="false">Pääsiäispäivä</easter>
    <easter offset="1" free="true">2. pääsiäispäivä</easter>
    <easter offset="39" free="true">Helatorstai</easter>
    <easter offset="49" free="true">Helluntai</easter>
    <date day="1" month="5" free="true">Vappu</date>
    <relative day="26" month="6" free="true" relation="last friday">Juhannusaatto</relative>
    <relative day="27" month="6" free="true" relation="last saturday">Juhannuspäivä</relative>
    <date day="12" month="6" free="true">Itsenäisyyspäivä</date>
    <date day="24" month="12" free="true">Jouluaatto</date>
    <date day="25" month="12" free="true">Joulupäivä</date>
    <date day="24" month="12" free="true">Tapaninpäivä</date>
</holidays>

=== DZunke/holidayChecker/share/lb_LU.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://www.heigl.org"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://www.heigl.org holidays.xsd"
>
    <date day="1" month="1" free="true">Neijoerschdag</date>
    <easter offset="0" free="false">Ouschter</easter>
    <easter offset="1" free="true">Ouschterméindeg</easter>
    <date day="1" month="5" free="true">Dag vun der Aarbecht</date>
    <easter offset="40" free="true">Christi Himmelfaart</easter>
    <easter offset="49" free="true">Péngscht</easter>
    <easter offset="50" free="true">Péngschtméindeg</easter>
    <date day="23" month="6" free="true">Groussherzogsgebuertsdag</date>
    <date day="15" month="8" free="true">Mariä Himmelfaart</date>
    <date day="1" month="11" free="true">Allerhellgen</date>
    <date day="25" month="12" free="true">Chrëschtdag</date>
    <date day="26" month="12" free="true">Stiefesdag</date>
</holidays>

=== DZunke/holidayChecker/share/CV.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Cape_Verde" lastChecked="2022-10-26">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Ano Novo</date>
	<date day="13" month="1" free="true" comment="Democracy Day">Dia da Liberdade e Democracia </date>
	<date day="20" month="1" free="true" comment="Heroes Day">Dia da Nacionalidade e dos Heróis Nacionais</date>
	<date day="1" month="5" free="true" comment="Heroes Day">Dia do Trabalhador</date>
	<date day="1" month="6" free="true" comment="Youth Day">Dia Mundial da Criança</date>
	<date day="5" month="7" free="true" comment="Independence Day">Dia da Independência Nacional</date>
	<date day="15" month="8" free="true" comment="Assumption day">Dia da Assunção</date>
	<date day="1" month="11" free="true" comment="ALl Saints Day">Dia de Todos os Santos</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Natal</date>
</holidays>

=== DZunke/holidayChecker/share/AZ.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Azerbaijan" lastChecked="2022-10-19">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Yeni il</date>
	<date day="2" month="1" free="true" comment="New Year's Day">Yeni il</date>
	<date day="20" month="1" free="true" comment="Martyrs' Day">Qara Yanvar</date>
	<date day="8" month="3" free="true" comment="Women's Day">Qadınlar günü</date>
	<date day="20" month="3" free="true" comment="Spring Festival">Novruz</date>
	<date day="21" month="3" free="true" comment="Spring Festival">Novruz</date>
	<date day="22" month="3" free="true" comment="Spring Festival">Novruz</date>
	<date day="23" month="3" free="true" comment="Spring Festival">Novruz</date>
	<date day="24" month="3" free="true" comment="Spring Festival">Novruz</date>
	<date day="9" month="5" free="true" comment="Victory Day over Fascism">Faşizm üzərinə qələbə günü</date>
	<date day="28" month="5" free="true" comment="Independence Day">Müstəqillik Günü</date>
	<date day="15" month="6" free="true" comment="National Salvation Day">Azərbaycan xalqının Milli Qurtuluş günü</date>
	<date day="26" month="6" free="true" comment="Azerbaijan Armed Forces Day">Azərbaycan Respublikasının Silahlı Qüvvələri günü</date>
	<date day="8" month="11" free="true" comment="Victory Day">Zəfər Günü</date>
	<date day="9" month="11" free="true" comment="Flag Day">Dövlət Bayrağı günü</date>
	<date day="31" month="12" free="true" comment="International Solidarity Day of Azerbaijanis">Dünya Azərbaycanlılarının Həmrəyliyi günü</date>
	<date day="1" month="10" calendar="islamic-umalqura" free="true" comment="Eid al-Fitr">Ramazan Bayramı</date>
	<date day="2" month="10" calendar="islamic-umalqura" free="true" comment="Eid al-Fitr">Ramazan Bayramı</date>
	<date day="10" month="12" calendar="islamic-umalqura" free="true" comment="Eid al-Adha">Qurban Bayramı</date>
	<date day="11" month="12" calendar="islamic-umalqura" free="true" comment="Eid al-Adha">Qurban Bayramı</date>
</holidays>

=== DZunke/holidayChecker/share/AL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Albania" lastChecked="2022-10-12">Wikipedia</resource>
    </resources>
    <dateFollowUp day="1" month="1" followup="tuesday" free="true" comment="New Year">Viti i Ri</dateFollowUp>
    <dateFollowUp day="2" month="1" followup="monday" free="true" comment="New Year">Viti i Ri</dateFollowUp>
    <dateFollowUp day="14" month="3" followup="monday" free="true" comment="Summer Day">Dita e Verës</dateFollowUp>
    <dateFollowUp day="22" month="3" followup="monday" free="true" comment="Nowruz">Dita e Nevruzit</dateFollowUp>
    <easter offset="0" free="true" comment="Catholic easter">Pashkët Katolike</easter>
    <easter offset="1" free="true" comment="Catholic easter">Pashkët Katolike</easter>
    <easterorthodox offset="0" free="true" comment="orthodox easter">Pashkët Ortodokse</easterorthodox>
    <easterorthodox offset="1" free="true" comment="orthodox easter">Pashkët Ortodokse</easterorthodox>
    <dateFollowUp day="1" followup="monday" free="true" month="5" comment="May Day">Dita Ndërkombëtare e Punonjësve</dateFollowUp>
    <dateFollowUp day="1" followup="monday" free="true" month="10" calendar="islamic-civil" comment="Eid al-Fitr">Bajrami i Madh</dateFollowUp>
    <dateFollowUp day="10" followup="monday" free="true" month="12" calendar="islamic-civil" comment="Eid al-Adha">Bajrami i Vogël</dateFollowUp>
    <dateFollowUp day="5" followup="monday" free="true" month="9" comment="Mother Theresa Day">Dita e Nënë Terezës</dateFollowUp>
    <dateFollowUp day="28" followup="monday" free="true" month="11" comment="Independence Day">Dita e Pavarësisë</dateFollowUp>
    <dateFollowUp day="29" followup="monday" free="true" month="11" comment="Liberation Day">Dita e Çlirimit</dateFollowUp>
    <dateFollowUp day="8" followup="monday" free="true" month="12" comment="National Youth Day">Dita Kombëtare e Rinisë</dateFollowUp>
    <dateFollowUp day="25" followup="monday" free="true" month="12" comment="Christmas Day">Krishtlindjet</dateFollowUp>
</holidays>
